name: len_den
description: Minimize Cash Flow Using Splitwise App

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  firebase_core: 0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.1+1
  google_sign_in: ^4.5.4
  google_fonts: ^1.1.0
  font_awesome_flutter: ^8.8.1
  contacts_service: ^0.4.6
  permission_handler: ^5.0.1+1
  flutter_snake_navigationbar: ^0.4.1+2
  flutter_login: ^1.0.14
  sliver_fab: ^1.0.0
  flip_card: ^0.4.4
  contactus: ^1.1.5
  image_picker: ^0.6.7+11
  auto_size_text: ^2.1.0
  dropdown_formfield: ^0.1.3
  modal_progress_hud: ^0.1.3
  collection: ^1.14.13
  cool_alert: ^1.0.1
  flutter_spinkit: ^4.1.2+1
  email_validator: ^1.0.6
  qr_flutter: ^3.2.0
  qrscan: ^0.2.17
  url_launcher: ^5.7.6
  shared_preferences: ^0.5.12+2
  introduction_screen: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/